### ISSUE TITLE
Computing the Damage Coefficients

### ISSUE THREAD

**Issue by austinrwg** [ClimateImpactLab/dscim-epa#27]
I am trying to get the DSCIM code to compute the damage coefficients in the damage_function_coefficients function. It says that if the file is not found, then it will compute the damage coefficients. However, I am facing an error: "Risk-aversion CEs not found. Please run CE_calculation.ipynb for `risk_aversion`."

That error message is from the risk_aversion_damages function in simple_storage.py. And the CE_calculation.ipynb does not seem to exist.

Any help would be very much appreciated! Thank you in advance.

**Comment by JMGilbert** [comment]
CE_calculation.ipynb is some legacy code that is long gone, sorry for the incorrect message. To correctly generate risk aversion CEs, use the [reduce_damages](https://github.com/ClimateImpactLab/dscim/blob/main/src/dscim/preprocessing/preprocessing.py#L67) function. 

This code is not exactly generalized for any possible use case, so if you can provide more information on your inputs and desired outputs I can probably be more helpful.

**Comment by austinrwg** [comment]
Thank you for your reply!

In input/damage_functions, there are precomputed files of damage coefficients based on discount rates. I am trying to reproduce those files. 

If the reduce_damages function is used, then will there be the necessary files to run the risk_aversion_damages function and, therefore, not have an error to compute the damage coefficients?

In the reduce_damages parameters, is there documentation on this? 
Not quite sure what these parameters should be, except for recipe = 'risk_aversion' and eta and perhaps sector as well.

**Comment by kemccusker** [comment]
Hi @austinrwg, thanks for your interest in this repository. The input data for calculating the damage function coefficients are several terabytes in size and are therefore not included in this repo. However, detailed descriptions of the underlying data and damage function calculations can be found in the following sources:
- [energy sector](https://www.nature.com/articles/s41586-021-03883-8)
- [mortality sector](https://academic.oup.com/qje/article/137/4/2037/6571943)
- [coastal sector](https://gmd.copernicus.org/articles/16/4331/2023/)
- [labor sector](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4221478)
- [agriculture sector](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4222020)
- [DSCIM User Manual](https://impactlab.org/research/data-driven-spatial-climate-impact-model-user-manual-version-092023-epa/) (synthesizes the information for all sectors and their combination)

**Comment by austinrwg** [comment]
Hello @kemccusker, thank you for your reply. Just a bit more help would be appreciated!

I thought that the DSCIM model has the functions to compute the damage coefficients, if the damage files are not provided. So, in code, I was wondering how to compute the coefficients under an alternative scenario, say 3%, 3.5%, or other discount rates?
